clean:
	rm -rf copy_here/*
	git restore copy_here/sample_file
	git restore can_this_be_overwritten/sample_file 
	git restore overwrite_folder/sample_file 
	git restore overwrite_folder/folder_with_files/file1
	git restore overwrite_folder/folder_with_files/file2
	git restore overwrite_folder/folder_with_files/file3
