restore:
	rm -rf all_file3/* python_files/* normal_files/* text_files/*
	git restore all_file3/file3.sample
	git restore python_files/sample.py
	git restore normal_files/file
	git restore text_files/sample.txt
	git restore file1 file2 file3 file1.py file2.py file3.py file1.txt file2.txt file3.txt
