restore:
	git restore delete_folder/try_to_delete_me/sample_file
	git restore delete_files/delete_this_file1.txt
	git restore delete_files/delete_this_file2.txt
	git restore delete_files/delete_this_file3.txt
	git restore delete_files/file1
	git restore delete_files/file2
	git restore delete_files/file3
	git restore delete_files/delete_files_not_this_folder/delete_this_file1.txt
	git restore delete_files/delete_files_not_this_folder/delete_this_file2.txt
	git restore delete_files/delete_files_not_this_folder/delete_this_file3.txt
