restore:
	git restore folder_with_files/file1
	git restore folder_with_files/file2
	git restore folder_with_files/file3
	git restore rename_me.txt
	git restore move_me.txt
	git restore move_and_rename_me.txt
clean:
	rm -rf renamed.txt move_here/* overwrite_folder/*
